---
reallycheat:
    prefix: "§cRCheat"
    alerts: 
        message: "{prefix} §8> §f{player} §7failed §f{module} §7VL §2{violation}"
        enable: true
        admin: false #This will cause the in-game cheat detector to send it to the person with the permissions below 
        permission: "reallycheat.notify"
    ban:
        commands:
            - "ban {player} You are hacking!"
        message: "{prefix} §8> §f{player} §chas been removed from server for hacking or abuse."
        enable: true
        randomize: false
        recentlogs:
            message: "{time}/{prefix} > {player} failed {module} VL {violation} | penalty: BAN"
    transfer:             
        ip: "play.example.net:19132" #If "usecommand" enabled, it will not work  
        usecommand:
            enable: false
            commands:
                - "transfer {player} play.example.net"
        message: "{prefix} §8> §f{player} §chas been kicked from server for hacking or abuse."
        randomize: false
        recentlogs:
            message: "{time}/{prefix} > {player} failed {module} VL {violation} | penalty: TRANSFER"       
    permissions:
        bypass:
            enable: false
            permission: "reallycheat.bypass"
...